### ISSUE TITLE
Support dotty as a build target

### ISSUE THREAD

**Issue by DamianReeves** [lemonlabsuk/scala-uri#154]
**Description**
It would be great if this project also cross compiled to dotty.

**Comment by theon** [comment]
Hi! Thanks for raising this. 

I'll give this go soon and let you know how it goes. I guess it may depend whether all dependencies have also been compiled for dotty.

**Comment by theon** [comment]
Dependencies not yet published for dotty below. See attempted build [here](https://travis-ci.org/github/lemonlabsuk/scala-uri/jobs/702535312)

 * parboiled2 (see https://github.com/sirthias/parboiled2/issues/210). We heavily use parboiled2 here. If it doesn't get cross compiled for dotty, it will be interesting to see what direction http4s go in.
 * cats (see https://github.com/typelevel/cats/issues/2553)
 * silencer ([won't be ported](https://github.com/ghik/silencer/issues/49)). Since warning suppression has been added to Scala 2.13.2 ([see note here](https://github.com/ghik/silencer#silencer-scala-compiler-plugin-for-warning-suppression)), we could look to remove this dependency and only have fatal-warnings for 2.13. Alternatively next major version bump of scala-uri should remove are requirement for warning suppression completely, since we will remove the [code we deprecated](https://github.com/lemonlabsuk/scala-uri/blob/master/build.sbt#L41)

**Comment by DamianReeves** [comment]
Thanks for the update. I guess the whole scala libraries start building for dotty in the 2nd/3rd quarter of 2020 isn't manifesting quite yet.

**Comment by theon** [comment]
Update:

 * silencer: dependency has been removed in scala-uri 3.0.0 (see f893ad5edc0c95a516466f20b18fce48f4a08b8e)
 * cats: Looks like dotty support has landed :+1:

So only blocked on parboiled2 now.

**Comment by hamnis** [comment]
@theon we are dropping parboiled2 in http4s, and using the new https://github.com/typelevel/cats-parse library instead

**Comment by theon** [comment]
Thanks for the heads up @hamnis. I suspected that might be the direction of travel; and have also started a rewrite removing parboiled2.

**Comment by tjarvstrand** [comment]
Hi there,

Is there any progress on this?

**Comment by theon** [comment]
Hi,

I think the quickest way for us to get onto Scala 3 would be progressing https://github.com/lemonlabsuk/scala-uri/pull/291

I've not taken a look yet; I think it is compiling, but needs some changes to pass the tests.

I'd also be keen to run the [benchmarks](https://github.com/lemonlabsuk/scala-uri-benchmarks) afterwards to confirm we are getting similar parsing performance

**Comment by armanbilge** [comment]
I would find this helpful at all. But besides the parboiled/cats-parse swap in #291 I suspect it will take some work to swap shapeless for shapeless3?

**Comment by theon** [comment]
Closing this as `4.0.0-M2` is now published for Scala 3, Scala 2.13 and Scala 2.12 (JVM and Scala.js). Thanks for everyone's help with this 🙇

**Comment by tjarvstrand** [comment]
Awesome!
