### ISSUE TITLE
Return Option[Url] from .parse() instead of potentially throwing exception

### ISSUE THREAD

**Issue by chuck-g** [lemonlabsuk/scala-uri#25]
I was surprised that the `Url.parse()` method didn't return an Option or Either, as this is a potentially error-prone operation, then I found `UrlParser.getOrThrow()` which explains the unwrapped return type. Instead of doing this and making the caller handle the exception, it would be better IMHO to return an `Option[Url]` or `Either[Url]`. You could also do this in a new method called `Url.parseOption` if you wanted to maintain current code.

Code Example:
```scala
val url = Url.parseOption("somethingBogus")
url mustEqual None
```

**Comment by theon** [comment]
There's not a huge amount of ways to get `Url.parse` to throw an exception (e.g. `"somethingBogus"` would return a `RelativeUrl`), but I do take your point!

I'm very happy to add a `Url.parseOption` method. Possibly also a `Url.parseTry` that returns a `Try[Url]` as well, because the exception thrown from an invalid URL does contain useful information such as which character was the first unexpected character.

What do you think?

**Comment by theon** [comment]
Thanks again for raising this. It's now released under version `1.4.0`. Let me know if you need anything else!

**Comment by chuck-g** [comment]
@GitCash send .01 bch to @theon

**Comment by GitCash** [comment]
Hey **theon**, user **chuck-g** tipped you **10000 bits** in Bitcoin Cash ( ~ **$5.13** ).

*[Click here to claim it!](https://gitcash.io/claim/theon)*

You can also add the "thumbs down" reaction to **chuck-g**'s comment above to prevent future tips.
