### ISSUE TITLE
Subdomains determining strange behaviour

### ISSUE THREAD

**Issue by yarik3571** [lemonlabsuk/scala-uri#318]
Looks like in some cases `subdomains` are not determined correctly. Seems it happens when there are hyphens (`-`) and numbers  in url.

**To Reproduce**
```scala
val url1 = Url.parse("http://475952.temp-dns.com/recipes/")
url1.hostOption // res0: Option[io.lemonlabs.uri.Host] = Some(475952.temp-dns.com)
url1.subdomain  // res1: Option[String] = None
url1.shortestSubdomain // res2: Option[String] = Some(475952)
url1.longestSubdomain // res3: Option[String] = Some(475952)
val url2 = Url.parse("https://allrecipes-01.web.app/")
url2.hostOption // res4: Option[io.lemonlabs.uri.Host] = Some(allrecipes-01.web.app)
url2.subdomain // res5: Option[String] = None
url2.shortestSubdomain // res6: Option[String] = Some(allrecipes-01)
url2.longestSubdomain // res7: Option[String] = Some(allrecipes-01)
```

**Comment by theon** [comment]
Hi @yarik3571. Thanks for raising this! This is a tricky one.

Took me a second to figure out what was going on. It's not to do with slashes or numbers, but because both `temp-dns.com` and `web.app` are listed on the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat) and scala-url currently always uses the longest public suffix on that list when determining the subdomain. As such, those URLs would be broken down like this:

```
https://blah.allrecipes-01.web.app/
        \--/ \-----------/ \-----/
         |         |          |
         |         |         [public suffix]
         |        [registered name]
        [subomdain]
```

Since `.app` is also on the public suffix list, a different domain ending with `.app` gets broken down differently by scala-uri. For example: 

```
https://blah.allrecipes-01.web2.app/
        \----------------/ \--/ \-/
                |           |    |
                |           |   [public suffix]
                |          [registered name]
               [subomdain]
```

TBH, I'm not sure how to solve this. If we add an option for scala-uri to use the shortest public suffix instead, it will behave as desired for the above URLs, but will act weird for other URLs. For example the subdomain for `https://www.bbc.co.uk/` would be returned as `www.bbc` rather than `www` because both `co.uk` and `.uk` are listed on the public suffix list.

**Comment by theon** [comment]
One option we could explore is allowing the user to define a filter to exclude public suffixes they don't want to use

**Comment by theon** [comment]
Ah, perfect; I'll absolutely add that. I didn't realise the public suffix list was divided into public and private domains. That solves the problem. TBH I think it makes most sense to have just the public domains as the default and require opt-in for the private domains.

**Comment by theon** [comment]
This is now fixed. I've released version `3.5.0` in which private domains from the public suffix list are no longer considered when determining subdomains.

Let me know if you ever need support for private domains (I'll likely only add support if someone requests it)

**Comment by gipeshka** [comment]
With the majority of previously public suffices gone now it's a bit harder to use the lib for suffices like `uk.com`, which in fact is really just an apexDomain, but for a client of the library it was a nice functionality to obtain an `example.uk.com` as an apex domain of a private suffix. As `uk.com` makes little sense and covers many real independent websites

**Comment by theon** [comment]
> With the majority of previously public suffices gone now it's a bit harder to use the lib for suffices like `uk.com`, which in fact is really just an apexDomain, but for a client of the library it was a nice functionality to obtain an `example.uk.com` as an apex domain of a private suffix. As `uk.com` makes little sense and covers many real independent websites.
> 
> Would it be possible to get the functionality back, maybe with a different method name?

Hey @gipeshka, I see both your use case where you'd like `example.uk.com` to be considered the apex domain and I can also see @yarik3571's where example should be a considered a subdomain instead.

I think they are both valid use-cases.

There is a website at https://uk.com, so it still makes sense on it's own.

I think the best solution is for me to add config to allow enabling/disabling of the private section of the public suffix list. I can add this :+1:

**Comment by gipeshka** [comment]
@theon sounds great
