### ISSUE TITLE
Question: How could I add "https://" to a URL without a scheme?

### ISSUE THREAD

**Issue by debajit** [lemonlabsuk/scala-uri#411]
I have some URLs without schemes, and in my case, I need to add "https://" to them (just prepending "https:" does not work for my case)

I tried the following, but that doesn't give me what I need:

```
val url = "google.com"
val uri = Url.parse(url)
uri.withScheme("https").toString
=> res50: String = "https:google.com"
```

When I use withScheme, is there an easy way I could add the "//" to the URL?

What is the easiest way to add a "https://" to a URL that does not have a scheme?

**Comment by theon** [comment]
Hey @debajit!

I'm afraid scala-uri doesn't provide anything to handle this out of the box, but I think you can achieve what you need with just a couple lines of code (see below)

### What's happening in the code you posted

Because those absolute URLs do not have a scheme they are technically not valid absolute URLs (according to RFC3986), and scala-uri's `parse` will return them as a relative URL (which they are valid as). Adding the scheme gives you a URL with a scheme and path, but no authority (like a `mailto:me@example.com` URL)

### How do get what you want

When you type `google.com/blah` into your browser it knows it should be treated as an absolute URL. If you type `google.ggg/blah` it knows it shouldn't and instead does a web search. It does this by checking if the first part of the string is a domain with a valid public suffix from the [public suffix list](https://publicsuffix.org/learn/). scala-uri does have support for the public-suffix list so we can achieve something similar like so:

```scala
val hostEnd = ":/?# \t\r\n".toSet
def parseMaybeNoScheme(url: String): Url = {
  val domainName = url.takeWhile(ch => !hostEnd(ch))
  if(DomainName(domainName).publicSuffix.nonEmpty) Url.parse("https://" + url) else Url.parse(url)
}
```

It behaves like this: 
```scala
scala> parseMaybeNoScheme("google.com")
val res4: io.lemonlabs.uri.Url = https://google.com

scala> parseMaybeNoScheme("http://google.com")
val res5: io.lemonlabs.uri.Url = http://google.com

scala> parseMaybeNoScheme("google.com/index.html")
val res6: io.lemonlabs.uri.Url = https://google.com/index.html

scala> parseMaybeNoScheme("/index.html")
val res7: io.lemonlabs.uri.Url = /index.html

scala> parseMaybeNoScheme("mailto:me@me.com")
val res8: io.lemonlabs.uri.Url = mailto:me@me.com
```

Let me know if that meets your needs?

**Comment by theon** [comment]
Closing this for now as I think this kind of "smart" parsing like this best lives outside of the scala-uri library itself, but feel free to comment or open a new issue with any further questions/discussion 🙇
