### ISSUE TITLE
Unexpected Url parsing 

### ISSUE THREAD

**Issue by pomadchin** [lemonlabsuk/scala-uri#42]
**Describe the bug**
In this particular example, during the url parsing there appears an extra character:

**To Reproduce**
```scala
val str = """data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif"""
val uri = Uri(str) 
//> data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif:
// ^ an extra : appeared
```

The question is how to properly handle some URIs with extra characters? Percent encoding during the parsing step?

**Comment by theon** [comment]
Hi,

Could I ask what version of scala-uri you are using. When I try with the latest version, there is no `Uri(String)` method:

```scala
scala> val str = """data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif"""
str: String = data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif

scala> val uri = Uri(str) 
                     ^
       error: type mismatch;
        found   : String
        required: java.net.URI
```

If I try to use `Url.parse`:

```scala
scala> val uri = Url.parse(str) 
io.lemonlabs.uri.decoding.UriDecodeException: Encountered '%' followed by a non hex number '^&'. It looks like this URL isn't Percent Encoded. If so, you can use eitherPercentDecoder(ignoreInvalidPercentEncoding=true) or NoopDecoder to suppress this Exception
  at io.lemonlabs.uri.decoding.PercentDecoder.go$1(PercentDecoder.scala:42)
  at io.lemonlabs.uri.decoding.PercentDecoder.decode(PercentDecoder.scala:48)
  at io.lemonlabs.uri.parsing.UrlParser.$anonfun$extractFragment$1(UrlParser.scala:198)
```

We get this exception because your URL includes a `%` which scala-uri assumes is being used to percent encode some characters, however it is not in this case. As you mentioned, Percent Encoding is the right call here. It's your responsibility to Percent Encode any reserved characters that are not being used for their reserved purpose (e.g. your URL has a `?` which normally indicates the start of the URL's query string, but I'm guessing that's not the intention here).

A blunt hammer approach would be something like:

```scala
import io.lemonlabs.uri.encoding.PercentEncoder

val pe = PercentEncoder(Set('%', '?', '#'))
val uri = Url.parse(pe.encode(str, "UTF-8"))

scala> uri.path.toStringRaw
res50: String = data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif

scala> uri.path.toString
res51: String = data/some__user--data%21%40%23%24%25%5E%26%2A%28%29%60~%7B%7D%5B%5D%5C%7C%3D%2B%2C%3F%27%3B%3C%3E%3B/files/my-data.tif
```

This works, but note that it will not work if you have a query string in `str`:

```scala
scala> val str = "/path/?/file.tif?width=10&height=10"
str: String = /path/?/file.tif?width=10&height=10

scala> val uri = Url.parse(pe.encode(str, "UTF-8"))
uri: io.lemonlabs.uri.Url = /path/%3F/file.tif%3Fwidth%3D10%26height%3D10

scala> uri.query
res54: io.lemonlabs.uri.QueryString =

scala> uri.path.toStringRaw
res55: String = /path/?/file.tif?width=10&height=10
```

There is no way for scala-uri to determine which `?` needs to be percent encoded and which `?` indicates the start of the query string. You will need some logic you side to percent encode the correct parts. However if `str` is always just a path, and never contains a query string, or fragment, etc, then the blunt hammer approach should be enough.

**Comment by theon** [comment]
Also worth noting:

If `str` is only a path (no query string or fragment), and you the latest scala-uri `1.4.9`, you can do this, which is maybe slightly easier than the previous examples:

```scala
val str = """data/some__user--data!@#$%^&*()`~{}[]\|=+,?';<>;/files/my-data.tif"""
val path = UrlPath.fromRaw(str)

// If you also need this path in a Url
val uri = Url().withPath(path)
```

**Comment by pomadchin** [comment]
Hey @theon, thanks for clarifying it for me :+1: and it looks like everything works; I think your answer resolves all the questions I had; if smth would come up I will reopen it / create a new one. Thanks for your help!
