### ISSUE TITLE
Become complaint with WHATWG url standard

### ISSUE THREAD

**Issue by RicoGit** [lemonlabsuk/scala-uri#83]
**Description**

There are many tests that already exist for checking parsing URL's. For example [web-platform-tests](https://github.com/web-platform-tests/wpt/tree/master/url/resources) (see test cases into *.json files). We can reuse these tests for free, for improving the quality of this project. What do you think?

Updated: 
Does 'scala-uri' parser support https://url.spec.whatwg.org/?

**Comment by theon** [comment]
This is a good suggestion. Thanks!

Generally speaking I am all for bringing in external test suites. It's a good way to increase coverage for little effort.

Thanks for making me aware of the WHATWG url spec. I've not read it, so can't comment on whether scala-uri conforms. I'll read through it and add the test suite.

**Comment by theon** [comment]
A little progress in ac95ccf1b2cd85a232f846a391dba86917ee7da8, however only 60/519 of the tests in `urltestdata.json` are passing. It will take a while to implement all the concepts in the WHATWG URL spec

**Comment by theon** [comment]
I am going to close this issue as I don't think I can commit to the scale of work required. It may even make most sense forking or starting a new library for WHATWG compliance rather than trying to support both RFC 3986 and WHATWG in a single library. Some of big changed needed:

* parsing needs to take an optional base URL in addition to the URL being parsed. [See 4.4](https://url.spec.whatwg.org/#url-parsing)
* the returned value must be able to include validation errors even for URLs successfully passed See [See 1.1](https://url.spec.whatwg.org/#validation-error)
